name: Student DevOps Flow - Python

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]

jobs:
  setup-validate-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Setup: Checkout code and set up Python
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 2. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 3. Validate code style (lint)
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      # 4. Run automated tests
      - name: Run tests with pytest
        run: |
          pip install pytest
          pytest

      # 5. Upload test results (optional, for visibility)
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: ./tests/

  # Optional: Deploy on main branch after passing all checks
  deploy:
    needs: setup-validate-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Here you would add your deployment step, e.g., to a cloud host, or NetSuite if integrated.
      - name: Deploy step placeholder
        run: echo "Deployment goes here (to cloud, server, etc.)"
