name: "Python_learning"

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/PythonFundamental/**

pool:
  vmImage: 'ubuntu-latest'

extends:
  template: templates/python-pipeline.yml
  parameters:
    workingDirectory: src/PythonFundamental
